### ISSUE TITLE
我想和你探讨交流一下点云配准  

### ISSUE THREAD

**Issue by Zhu550400438** [YZHUA/k4PCS_-modified#2]
可以知道你的QQ么？

**Comment by Zhu550400438** [comment]
我也是学了一点点，不太精通发自我的华为手机-------- 原始邮件 --------发件人： YZHUA <notifications@github.com>日期： 2019年9月5日周四 20:50收件人： YZHUA/k4PCS_-modified <k4PCS_-modified@noreply.github.com>抄送： Zhu550400438 <550400438@qq.com>, Author <author@noreply.github.com>主    题： Re: [YZHUA/k4PCS_-modified] 我想和你探讨交流一下点云配准   (#2)Closed #2.

**Comment by YZHUA** [comment]
我现在已经不研究这一块了，然后你应该也没有这方面的兴趣了吧。
